# Database Config
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: dev
  labels:
    app: backend
data:
  db-host: "mysql-svc.dev.svc.cluster.local"
  db-port: "3306"
  db-name: "mysqldb"
  path: "/app/uploads"
  node-env: "dev"
  port: "3000"
