#==================================================
# Backend Database ConfigMap
# Stores non-sensitive configs for MySQL connection
#==================================================
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: dev
  labels:
    app: backend
data:
  db-host: "mysql-svc"
  db-port: "3306"
  db-name: "mysqldb"

  upload-path: "/app/uploads"
  node-env: "dev"
  port: "3000"
