# Database Config
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
  namespace: dev
  labels:
    app: node-app
data:
  host: "mysql-svc.dev.svc.cluster.local"
  port: "3306"
  dbname: "mysqldb"
