#=====================================
# MySQL Database ConfigMap
# Stores non-sensitive MySQL config
#=====================================
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: dev
  labels:
    app: mysql-db
data:
  # Used by mysql container entrypoint only during first initialization
  MYSQL_DATABASE: "mysqldb"
